import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useApp, studyService } from '../application/AppContext';
import type { LessonProgress, ReviewCardState } from '../domain/models';
import { Icon } from '../ui/Icon';

export default function DashboardPage() {
  const { profile } = useApp(); const [progress, setProgress] = useState<LessonProgress[]>([]); const [due, setDue] = useState<ReviewCardState[]>([]);
  useEffect(() => { void Promise.all([studyService.listProgress(), studyService.listDueReviews()]).then(([p, d]) => { setProgress(p); setDue(d); }); }, []);
  const completed = progress.filter((item) => item.completed).length; const pct = Math.round((completed / 72) * 100); const next = Math.min(72, completed + 1); const week = Math.ceil(next / 3); const lesson = ((next - 1) % 3) + 1;
  return <div className="page dashboard-page"><section className="hero-card"><div><span className="eyebrow">SEMANA {Math.max(1, profile.currentWeek)} · NIVEL {profile.currentLevel}</span><h1>{profile.displayName ? `Hola, ${profile.displayName}` : 'Tu inglés empieza aquí'}</h1><p>Un circuito se construye conexión por conexión. Hoy suma una nueva.</p><div className="hero-actions"><Link className="button button-accent" to={`/leccion/w${String(week).padStart(2, '0')}-l${String(lesson).padStart(2, '0')}`}><Icon name="play" />{completed ? 'Continuar aprendiendo' : 'Comenzar primera lección'}</Link><span>{profile.dailyGoalMinutes} min de meta diaria</span></div></div><div className="circuit-illustration" aria-hidden="true"><span className="orb orb-one"/><span className="orb orb-two"/><span className="orb orb-three"/><Icon name="bolt" size={48}/></div></section>
    <section className="metric-grid" aria-label="Resumen de progreso"><article><span className="metric-icon green">🔥</span><div><strong>{profile.currentStreak}</strong><span>Días de racha</span></div></article><article><span className="metric-icon blue">◷</span><div><strong>{profile.totalStudyMinutes}</strong><span>Minutos estudiados</span></div></article><article><span className="metric-icon purple">✓</span><div><strong>{completed}<small>/72</small></strong><span>Lecciones</span></div></article><article><span className="metric-icon amber">↻</span><div><strong>{due.length}</strong><span>Repasos pendientes</span></div></article></section>
    <div className="dashboard-grid"><section className="panel current-lesson"><div className="section-heading"><div><span className="eyebrow">SIGUIENTE CONEXIÓN</span><h2>Semana {week} · Lección {lesson}</h2></div><span className="duration">≈ 50 min</span></div><h3>{next === 1 ? 'Saludar con confianza' : 'Continúa tu ruta personal'}</h3><p>Vocabulario, conversación, escucha, ejercicios y una práctica oral.</p><div className="progress-track"><span style={{ width: `${pct}%` }} /></div><small>{pct}% del curso completado</small><Link className="text-link" to="/ruta">Ver ruta completa →</Link></section>
      <section className="panel goal-panel"><div className="section-heading"><h2>Meta de hoy</h2><span>{Math.min(profile.totalStudyMinutes, profile.dailyGoalMinutes)} / {profile.dailyGoalMinutes} min</span></div><div className="goal-ring" style={{ '--progress': `${Math.min(100, (profile.totalStudyMinutes / profile.dailyGoalMinutes) * 100)}%` } as React.CSSProperties}><span>{Math.min(profile.totalStudyMinutes, profile.dailyGoalMinutes)}</span><small>min</small></div><p>La constancia supera a la intensidad. Estudia a tu ritmo.</p></section></div>
    <section className="panel week-preview"><div className="section-heading"><div><span className="eyebrow">TU SEMANA</span><h2>Primer contacto</h2></div><Link className="text-link" to="/ruta">Ver detalles</Link></div><div className="week-days">{['Saludar', 'Presentarme', 'Alfabeto', 'Práctica', 'Sonidos', 'Repaso', 'Libre'].map((label, i) => <div key={label} className={i === completed ? 'today' : i < completed ? 'done' : ''}><span>{i < completed ? '✓' : i + 1}</span><b>{label}</b><small>{i < 3 ? 'Lección' : i < 5 ? 'Práctica' : i === 5 ? 'Repaso' : 'Descanso'}</small></div>)}</div></section>
  </div>;
}

