import { useEffect, useState, type FormEvent } from 'react';
import { useApp, studyService, syncService } from '../application/AppContext';
import { firebaseConfigurationState } from '../infrastructure/firebase/config';
import { observeAuth, signInWithEmail, signOutFromFirebase } from '../infrastructure/firebase/auth';
import { Icon } from '../ui/Icon';

export default function SettingsPage() {
  const { profile, setProfile, syncStatus, setSyncStatus } = useApp(); const [draft, setDraft] = useState(profile); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [user, setUser] = useState<import('firebase/auth').User | null>(null); const [message, setMessage] = useState(''); const firebaseState = firebaseConfigurationState();
  useEffect(() => setDraft(profile), [profile]);
  useEffect(() => { if (!firebaseState.ready) return; let unsubscribe: undefined | (() => void); void observeAuth(setUser).then((value) => { unsubscribe = value; }); return () => unsubscribe?.(); }, [firebaseState.ready]);
  const login = async (event: FormEvent) => { event.preventDefault(); setMessage(''); try { const next = await signInWithEmail(email, password); setUser(next); setPassword(''); setMessage('Sesión iniciada. Ya puedes sincronizar.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'No fue posible iniciar sesión.'); } };
  const exportBackup = async () => { const data = await studyService.exportBackup(); const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `english-circuit-${new Date().toISOString().slice(0,10)}.json`; link.click(); URL.revokeObjectURL(url); };
  const importBackup = async (file?: File) => { if (!file) return; try { const parsed: unknown = JSON.parse(await file.text()); if (!confirm('Se reemplazará el progreso local después de crear una copia descargable. ¿Continuar?')) return; await exportBackup(); await studyService.importBackup(parsed); location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'El respaldo no es válido.'); } };
  return <div className="page settings-page"><header className="page-header"><span className="eyebrow">PREFERENCIAS Y PRIVACIDAD</span><h1>Configuración</h1><p>Tu perfil funciona localmente y no está limitado a una sola persona.</p></header>
    <form className="panel settings-form" onSubmit={async (event) => { event.preventDefault(); await setProfile(draft); setMessage('Preferencias guardadas.'); }}><h2>Perfil de aprendizaje</h2><div className="form-grid"><label className="field"><span>Nombre para saludarte</span><input value={draft.displayName} onChange={(e)=>setDraft({...draft,displayName:e.target.value})} maxLength={60}/></label><label className="field"><span>Meta diaria</span><select value={draft.dailyGoalMinutes} onChange={(e)=>setDraft({...draft,dailyGoalMinutes:Number(e.target.value)})}>{[15,30,45,60].map(v=><option key={v} value={v}>{v} minutos</option>)}</select></label><label className="field"><span>Tema</span><select value={draft.theme} onChange={(e)=>setDraft({...draft,theme:e.target.value as typeof draft.theme})}><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></label><label className="field"><span>Velocidad de voz</span><select value={draft.speechRate} onChange={(e)=>setDraft({...draft,speechRate:Number(e.target.value)})}><option value="0.7">Lenta</option><option value="0.85">Clara</option><option value="1">Normal</option></select></label></div><div className="toggle-row"><label><input type="checkbox" checked={draft.translationsEnabled} onChange={(e)=>setDraft({...draft,translationsEnabled:e.target.checked})}/><span>Mostrar traducciones</span></label><label><input type="checkbox" checked={draft.experimentalRecognition} onChange={(e)=>setDraft({...draft,experimentalRecognition:e.target.checked})}/><span>Reconocimiento experimental</span></label></div><button className="button button-primary" type="submit">Guardar preferencias</button></form>
    <section className="panel"><div className="section-heading"><div><h2>Sincronización opcional</h2><p>{firebaseState.message}</p></div><span className={`sync-badge status-${syncStatus}`}><Icon name="sync" size={16}/>{syncStatus}</span></div>{firebaseState.ready ? user ? <div className="auth-row"><div><b>{user.email}</b><small>Correo verificado · namespace educativo aislado</small></div><button className="button button-primary" onClick={()=>void syncService.flush(user.uid,setSyncStatus)}>Sincronizar ahora</button><button className="button button-ghost" onClick={async()=>{await signOutFromFirebase();setUser(null);}}>Cerrar sesión</button></div> : <form className="auth-form" onSubmit={login}><label className="field"><span>Correo</span><input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="username"/></label><label className="field"><span>Contraseña</span><input type="password" required value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="button button-primary">Iniciar sesión</button><p>Solo se acepta una cuenta con correo verificado. La contraseña nunca se guarda localmente.</p></form> : <p className="notice">Registra “English Circuit Web” en Firebase y completa `.env`. No se reutiliza el App ID financiero.</p>}</section>
    <section className="panel"><h2>Respaldo y datos locales</h2><p>El respaldo incluye perfil, configuración, progreso, tarjetas, estadísticas y sesiones. Excluye grabaciones, tokens, credenciales y cualquier dato financiero.</p><div className="button-row"><button className="button button-primary" onClick={()=>void exportBackup()}>Exportar JSON</button><label className="button button-ghost file-button">Importar JSON<input type="file" accept="application/json" onChange={(e)=>void importBackup(e.target.files?.[0])}/></label><button className="button button-danger" onClick={async()=>{if(confirm('¿Eliminar todo el progreso local? Esta acción no se puede deshacer.')){await studyService.clearAll();location.reload();}}}>Reiniciar progreso</button><button className="button button-ghost" onClick={async()=>{if(confirm('¿Eliminar todas las grabaciones locales?')) await studyService.recordings().clear();}}>Eliminar grabaciones</button></div></section>
    <section className="panel resources"><h2>Recursos gratuitos oficiales</h2><div>{[['USA Learns','https://www.usalearns.org/'],['VOA Learning English','https://learningenglish.voanews.com/'],['British Council LearnEnglish','https://learnenglish.britishcouncil.org/'],['All About Circuits','https://www.allaboutcircuits.com/']].map(([label,url])=><a href={url} target="_blank" rel="noreferrer" key={label}>{label}<span>↗</span></a>)}</div></section>
    <section className="panel privacy"><h2>Privacidad en lenguaje claro</h2><p>El perfil, progreso, sesiones y grabaciones se guardan primero en tu dispositivo. Si inicias sesión, solo los datos educativos compatibles se sincronizan a Firestore. Las grabaciones nunca se suben. No hay publicidad, rastreadores ni venta de datos.</p><p>Puedes exportar, importar, reiniciar el progreso o borrar grabaciones desde esta pantalla. Firebase Authentication conserva la sesión según su política, pero English Circuit no guarda contraseñas.</p></section>{message&&<div className="toast" role="status">{message}</div>}
  </div>;
}

